import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Bell,
  BellRing,
  Bot,
  Box,
  Brain,
  Calendar,
  Camera,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircuitBoard,
  Copy,
  Cpu,
  Database,
  Download,
  Ear,
  ExternalLink,
  Eye,
  FileKey2,
  FileText,
  Filter,
  Folder,
  Gauge,
  GraduationCap,
  Grid2x2,
  HelpCircle,
  History,
  Home,
  Inbox,
  Info,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Loader2,
  Lock,
  LogOut,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  MoreHorizontal,
  Package,
  PanelLeft,
  Pencil,
  Pin,
  PinOff,
  Play,
  Plug,
  Plus,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Speech,
  Square,
  Sun,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  UploadCloud,
  User,
  Users,
  Volume2,
  VolumeX,
  Workflow,
  Wrench,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type Icon = LucideIcon;

// docs/UI.md: "Icons: lucide only, by name... no other icon set." The
// kit owns the name -> component registry, keyed by kebab-case (never
// a lucide component's own PascalCase export name) so app code and JSON
// page data alike reference an icon the same way. Merged from Home's
// and the Stack's own registries (ui-v0.1.0): where the two chose a
// different lucide component for the same semantic name, one is picked
// and the other's call sites are updated - never two names for one
// meaning.
export const icons = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  bell: Bell,
  "bell-ring": BellRing,
  bot: Bot,
  box: Box,
  brain: Brain,
  calendar: Calendar,
  camera: Camera,
  check: CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "circuit-board": CircuitBoard,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  download: Download,
  ear: Ear,
  "external-link": ExternalLink,
  eye: Eye,
  "file-key": FileKey2,
  "file-text": FileText,
  filter: Filter,
  folder: Folder,
  gauge: Gauge,
  "graduation-cap": GraduationCap,
  "grid-2x2": Grid2x2,
  history: History,
  home: Home,
  inbox: Inbox,
  info: Info,
  "key-round": KeyRound,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "layout-list": LayoutList,
  loader: Loader2,
  lock: Lock,
  "log-out": LogOut,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  package: Package,
  "panel-left": PanelLeft,
  pencil: Pencil,
  pin: Pin,
  "pin-off": PinOff,
  play: Play,
  plug: Plug,
  plus: Plus,
  puzzle: Puzzle,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  "settings-2": Settings2,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  speech: Speech,
  square: Square,
  sun: Sun,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  trash: Trash2,
  "upload-cloud": UploadCloud,
  user: User,
  users: Users,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
} as const;

export type IconName = keyof typeof icons;
export const iconNames = Object.keys(icons) as IconName[];

export function getIcon(name: string): LucideIcon {
  const icon = icons[name as IconName];
  if (!icon) console.warn(`Unknown icon: ${name}`);
  return icon ?? HelpCircle;
}
